version: '3.9'

services:
  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'snippetbox'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local